name: klikit
description: Kilkit Enterprise App

publish_to: 'none'

version: 1.0.0+100

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.4
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.4
  equatable: ^2.0.5
  collection: ^1.16.0
  json_serializable: ^6.3.1
  flutter_bloc: ^8.1.1
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5
  intl: ^0.17.0
  flutter_native_timezone: ^2.0.0
  shimmer: ^2.0.0
  web_socket_channel: ^2.2.0
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.1
  defer_pointer: ^0.0.2
  flutter_local_notifications: ^12.0.4
  package_info_plus: ^3.0.2
  audioplayers: ^2.0.0
  permission_handler: ^10.3.0
  flutter_pos_printer_platform: 1.1.0
  percent_indicator: ^4.2.2
  device_info_plus: ^4.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  badges: ^3.1.1
  flutter_expanded_tile: ^0.3.7
  flutter_easyloading: ^3.0.5
  scrollable_list_tab_scroller: 1.1.0
  flutter_blue_plus: 1.5.2
  slack_logger: ^1.0.6
  crypto: ^3.0.2
  wakelock: ^0.6.2
  salesiq_mobilisten: ^3.1.1
  scrollable_positioned_list: 0.3.5
  # firebase
#  firebase_core: ^2.11.0
#  firebase_core_desktop: ^1.0.2
#  firebase_messaging: ^14.5.0
#  firebase_remote_config: ^3.0.9
#  firebase_analytics: ^10.1.0
#  firebase_crashlytics: ^3.0.11

  docket_design_template:
    git:
      url: https://github.com/angripa1992/docket_design_template.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - assets/translations/
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/docket_fonts/
    - assets/env/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100