name: klikit
description: Kilkit Enterprise App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.4
  dio: ^4.0.6
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/translations/
     - assets/images/
     - assets/images/1.5x/
     - assets/images/2.0x/
     - assets/images/3.0x/
     - assets/images/4.0x/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Bold.otf
          weight: 700
        - asset: assets/fonts/Aeonik-Medium.otf
          weight: 500
        - asset: assets/fonts/Aeonik-Regular.otf
          weight: 400
        - asset: assets/fonts/Aeonik-Light.otf
          weight: 300
