name: Build Windows Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code using action
      uses: actions/checkout@v2
    - name: Test connection
      run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.18.5'  # Adjust to the Flutter version you're using
        channel: any
    - name: 'Checkout Flutter 2.18.5'
      shell: bash
      run: |
         cd $FLUTTER_HOME;
         git fetch --tags;
         git checkout 2.18.5;
         flutter --version;
    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows executable
      run: flutter build windows

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/windows

    - name: Release on GitHub
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: build/windows/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
