name: Build Windows Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clear cache
      uses: actions/github-script@v6
      with:
        script: |
              console.log("About to clear")
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              for (const cache of caches.data.actions_caches) {
                console.log(cache)
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
              console.log("Clear completed")
    - name: Checkout code using action
      uses: actions/checkout@v2


    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        architecture: x64
#        flutter-version: '3.4.0-17.1.pre'  # Adjust to the Flutter version you're using
        flutter-version: '3.3.9'  # Adjust to the Flutter version you're using
#    - name: 'Checkout Flutter 3.0.0'
#      shell: bash
#      run: |
#        echo $FLUTTER_HOME;
#         cd $FLUTTER_HOME;
#         git fetch --tags;
#         git checkout 3.3.9;
#         flutter --version;
    - name: Flutter clean
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Install dependencies
      run: flutter doctor -v

    - name: Build Windows executable
      run: flutter build windows


    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/windows

    - name: Release on GitHub
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: build/windows/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
